global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'telegram-alerts'

  routes:
    - match:
        severity: critical
      group_wait: 5s
      repeat_interval: 10m
      receiver: 'telegram-alerts'

receivers:
  - name: 'telegram-alerts'
    telegram_configs:
      - bot_token: '8318506270:AAGzEwBW46VE-_K_Z__Gcuh8MiPOvBdaVMM'
        chat_id: -1002508752139
        message_thread_id: 3716
        send_resolved: true
        parse_mode: 'HTML'
        message: |
          {{ range .Alerts }}
          {{ if eq .Status "firing" }}ðŸ”´ ALERT
          
          MQ server: {{ .Labels.alertname }}:
          {{ .Annotations.summary }}. {{ .Annotations.description }}{{ else }}âœ… RESOLVED
          
          MQ server: {{ .Labels.alertname }}:
          {{ .Annotations.summary }}. {{ .Annotations.description }}{{ end }}
          {{ end }}